# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 376cc94f9c164da1776ec3e612edeee6606feea9919cb9ae860ed77042de43f8610d9793973e51698e9b8d60309499d16fdeeb9f781548a14d7babbd49302ed5

test:
  secret_key_base: 2578344c73eb996d201c51e35901df909dcca8874882e8bb699dc5692e6cfde0ed0a3be0c1c8dcff0647d6fe9ad7d12e0d391224684da4ebfa38259ca990ce14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
